apiVersion: v1
kind: Service
metadata:
  labels:
    app: push-notification
  name: push-notification-service
  namespace: default
spec:
  ports:
  - nodePort: 32431
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: push-notification
  type: NodePort
